spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # Spring AI 模型配置（以 OpenAI 为例，其他模型可替换）
  ai:
    ollama:
      init:
        timeout: 60m
        max-retries: 3
        embedding:
          additional-models:
            - qwen3-embedding:0.6b
        pull-model-strategy: when_missing
      baseUrl: ${OLLAMA_BASE_URL}
      embedding:
        model: qwen3-embedding:0.6b
      chat:
        model: qwen3.5:4b


# 日志配置（便于调试流程）
logging:
  level:
    org.langchain4j: DEBUG
    com.example: DEBUG

